---
- name: installin lamp stack
  hosts: all
  become: yes
  tasks:
      - name: installng apache2
        apt:
           name: apache2
           update_cache: yes
           state: present
      - name: installing my-sql server
        apt: 
           name: mysql-server
           state: present
      - name: installing php
        apt:
           name: php
           state: present
      - name: libapache2-mod-php 
        apt:
           name: libapache2-mod-php 
           state: present
      - name: php-mysql
        apt:
           name: php-mysql
           state: present
      - name: installing  php-cli
        apt:
           name: php-cli
           state: present
           
