- name: installing spring boot application as a service
  hosts: all
  become: yes
  tasks:
  - name: update the package
    apt:
      name: openjdk-11-jdk
      update_cache: yes
      state: present
  - name: create a directory
    file:
      dest: /usr/share/springpetclinic
      state: directory
  - name: downloding the spring boot jar file
    get_url:
      url: https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
      dest: /usr/share/springpetclinic
  - name: add user spring
    user:
      name: spring
      password: pk07
  - name: change file owner ship
    file:
      path: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
      owner: spring
      mode: 0500
# using spring.service file
  - name: copy systemctl file
    copy:
      src: /home/ansibleadmin/spring.service
      dest: /etc/systemd/system/
